apiVersion: v2
name: sonarr
description: A Helm chart for Sonarr using lib-chart
type: application
version: 0.0.8
appVersion: "4.0.16.2944"
keywords:
  - sonarr
  - media-center
dependencies:
  - name: lib-chart
    version: "0.0.9"
    repository: "oci://ghcr.io/orhayoun-eevee"
maintainers:
  - name: Sonarr Team
home: https://sonarr.tv/
